# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  auto_review:
    enabled: true
    drafts: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"
      - "DO NOT MERGE"

  path_filters:
    - "!bun.lock"
    - "!**/*.lock"
    - "!**/cov_profile/**"
    - "!**/testdata/**"
    - "!**/*.generated.ts"

  path_instructions:
    - path: "**"
      instructions: |
        You are a Senior Bun + TypeScript Software Engineer.
        Review the code based on the following criteria:

        1. **Bun Runtime Best Practices**:
           - Ensure code aligns with Bun runtime and `package.json` scripts.
           - Prefer Bun/Node APIs (`process`, `node:fs`, `node:path`) over Deno APIs.
           - Check CLI/runtime behavior under Bun (arguments, exits, env handling).

        2. **OpenTUI & CLI Structure**:
           - Review OpenTUI usage (`@opentui/react`, native primitives/hooks) for regressions.
           - Ensure Cliffy command wiring is coherent and options/subcommands behave correctly.

        3. **TypeScript & Logic**:
           - Enforce strict TypeScript typing (avoid `any`).
           - Focus on logic errors, security risks, and performance issues.
           - Do not comment on formatting (assume automated formatters handle it).

        4. **Tone**:
           - Keep feedback concise, constructive, and "chill".

chat:
  auto_reply: true
