comment:
  layout: "header, diff, flags, files"
  require_changes: false
  after_n_builds: 2

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 0%

flags:
  tui:
    paths:
      - apps/tui/
    carryforward: true
  vscode:
    paths:
      - apps/vscode/
    carryforward: true