blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/naatin777/gitogito/discussions
    about: Please ask questions or discuss ideas here instead of opening an issue.
