name: Core Test & Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.13"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm check

      - name: Run TUI tests
        run: pnpm --filter @gitogito/tui test

      - name: Run shared package tests
        run: pnpm --filter @gitogito/shared test

      - name: Run core tests
        run: pnpm --filter @gitogito/core test

      - name: Run TUI coverage
        run: pnpm --filter @gitogito/tui test:coverage

      - name: Run shared coverage
        run: pnpm --filter @gitogito/shared test:coverage

      - name: Run core coverage
        run: pnpm --filter @gitogito/core test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./apps/tui/.coverage/lcov.info,./packages/shared/.coverage/lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
